mysite/urls.py
from django.contrib import admin
from django.urls import include, path

# from . import views


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
#path('polls/', include('polls.urls')),

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.category, name='category'),
    path('<int:category_id>/', views.index, name='index'),
    path('<int:category_id>/<int:question_id>/', views.detail, name='detail'),
    path('<int:category_id>/<int:question_id>/results/', views.results, name='results'),
    path('<int:category_id>/<int:question_id>/vote/', views.vote, name='vote'),
]


# urlpatterns = [
#     path('', views.index, name='index'),
#     # ex: /polls/5/
#     # Add path calls for new views!
#     # detail() method will run and display whatever ID you provide in URL
#     path('<int:question_id>/', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     path('<int:question_id>/results/', views.results, name='results'),
#     # ex: /polls/5/vote/
#     path('<int:question_id>/vote/', views.vote, name='vote'),
# ]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

class Category(models.Model):
    category_name = models.CharField(max_length = 50, default='SOME STRING')
    category_desc = models.CharField(max_length = 500, default='SOME STRING')
    category_count = models.IntegerField(default=0)
    
    def __str__(self):
        return self.category_name


class Question(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # Important to add this method when dealing w/ interactive promopt
    def __str__(self):
        return self.question_text
    # Add custom date/time method

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
  # Relationship defined w/ Foreign Key
  # FK tells Django each key related to single Question
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

"""class Result(models.Model):
    result_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # Important to add this method when dealing w/ interactive promopt
    def __str__(self):
        return self.result_text
    # Add custom date/time method"""

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
#from django.views import generic
from .models import Choice, Question, Category
from django.utils import timezone

# This code loads template called poll/index/html and passes it a context. The context in a dictionary mapping template variable names to Python objects
def category(request):
    category_list = Category.objects.all()
    context = {
        'category_list': category_list,
        }
    return render(request, 'polls/category.html', context)

def index(request, category_id):
    #template_name = 'polls/index.html'
    cat_question = Question.objects.filter(category=category_id)
    context = {
        'cat_question': cat_question,
        'category_id': category_id,
        }
    return render(request, 'polls/index.html', context)
    


def detail(request, category_id, question_id):
    #model = Question
    #emplate_name = 'polls/detail.html'
    question = get_object_or_404(Question, pk = question_id)
    context = {
        'question': question,
        'category_id': category_id,
        }
    return render(request, 'polls/detail.html', context)

    """def get_queryset(self):
        
        Excludes any questions that aren't published yet.
        
        return Question.objects.filter(pub_date__lte=timezone.now())"""


"""class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'"""
def results(request, category_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {
        'question': question,
        'category_id': category_id,
        }
    return render(request, 'polls/results.html', context)


def vote(request, category_id, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'category_id': category_id,
            'question': question,
            'error_message': "You didn't select a choice!",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(category_id, question.id,)))

"""class ExtraView(generic.DetailView):
    model = Result
    template_name = 'polls/extra.html'

    def get_queryset(self):
        
        Return the last five published questions (not including those set to be
        published in the future).
        
        return Result.objects.filter(
            pub_date__lte=timezone.now()
        )
        """

polls/templates/polls/category.html
<!-- STYLES -->
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap"
  rel="stylesheet"
/>

<!-- Links to Questions -->
<!-- Name argument defined in path() functions in polls.urls model. -->

{% if category_list %}
<div class="content_container">
  <div class="polls">
  <h1> <p style="color: white">THE POLLS APP </h1></p>
  </div>
  <b><h3> <p style="margin-top: -50px"> AVAILABLE POLLS:<p></b></h3>
  <BR>
  <ul>
    {% for category in category_list %}
    <li>
      <a href="{% url 'polls:index' category.id %}">{{ category.category_name }}</a
      >
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No polls are available.</p>
  {% endif %}
  <div class="pika"><img src="https://www.pngmart.com/files/2/Pikachu-Transparent-Background.png" alt="pika" style="width:200px;height:200px;"></div>
</div>

<!-- V1 Hardcoded, tightly coupled approach -->
<!-- Makes it challenging to change URLs on projects w/ lots of templates -->
<!-- {% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

polls/templates/polls/detail.html
<!-- STYLES -->
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap"
  rel="stylesheet"
/>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
<!-- This template displays a radio button for each question, the value is associated with an ID -->

<!--Each radio button is a choice. When someone selects a choice and submits form, POST dad choice=# -->


<div class="content_container">
  <h1>{{ question.question_text }}</h1>
  
<label class="error">
  {% if error_message %}
  <p><strong><h4>{{ error_message }}</strong></h4>
  {% endif %}</label> 
  <br>
  <br>
  
  <form class="form" action="{% url 'polls:vote' category_id question.id %}" method="post">
    {% csrf_token %} {% for choice in question.choice_set.all %}
    <input 
      type="radio" 
      name="choice"
      id="choice{{ forloop.counter }}"
      value="{{ choice.id }}"
    /><span>
    <label class="choice" for="choice{{ forloop.counter }}" >{{ choice.choice_text }}
    </span>
    </label><br>
    {% endfor %}
    <input class="button" type="submit" value="Vote" />
  </form>

</div>

polls/templates/polls/extra.html
<!-- STYLES -->
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap"
  rel="stylesheet"
/>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
<!-- This template displays a radio button for each question, the value is associated with an ID -->

<!--Each radio button is a choice. When someone selects a choice and submits form, POST dad choice=# -->


<div class="content_container">
    <h1>ABOUT THIS APP</h1>
    <div class = "result_text"><strong>{{ result.result_text }}</strong></div>
<div class = "description">   
    <br>
    <br>
     ITS A GENNERAL POLLS APP.<br>
    <strong>It consists of two parts:</strong>
    <br>
<li >A public site that lets people view polls and vote in them.</li>
<li>An admin site that lets you add, change, and delete polls.</li>
</div>
<br>
<a href="https://docs.djangoproject.com/en/3.1/intro/tutorial01/">Check out the official django tutorial</a>
<strong><a href="http://127.0.0.1:8000">Go back to main polls page</a></strong>
</div>

polls/templates/polls/index.html
<!-- STYLES -->
{% load static %}
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap"
  rel="stylesheet"
/>

<!-- Links to Questions -->
<!-- Name argument defined in path() functions in polls.urls model. -->

{% if latest_question_list %}
<div class="content_container">
  <div class="polls">
  <h1> <p style="color: white">THE POLLS APP </h1></p>
  </div>
  <b><h3> <p style="margin-top: -50px"> AVAILABLE POLLS:<p></b></h3>
  <BR>
  <ul>
    {% for question in latest_question_list %}
    <li>
      <a href="{% url 'polls:detail' question.id %}"
        >{{ question.question_text }}</a
      >
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <p>No polls are available.</p>
  {% endif %}
  <div class="pika"><img src="https://www.pngmart.com/files/2/Pikachu-Transparent-Background.png" alt="pika" style="width:200px;height:200px;"></div>
</div>

<!-- V1 Hardcoded, tightly coupled approach -->
<!-- Makes it challenging to change URLs on projects w/ lots of templates -->
<!-- {% if latest_question_list %}
<ul>
  {% for question in latest_question_list %}
  <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %} -->

polls/templates/polls/results.html
<!-- STYLES -->
{% load static %}

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap"
  rel="stylesheet"
/>

<div class="content_container">
  <h1>{{ question.question_text }}</h1>
  <div class ="result">
  <ul>
    {% for choice in question.choice_set.all %}
    <li>
      {{ choice.choice_text }} -<b> {{ choice.votes }}
      vote{{choice.votes|pluralize }}</b>
    </li>
    {% endfor %}
  </ul>
  </div>
  <a class="vote_again" href="{% url 'polls:category' %}"
    >Vote again</a>
</div>